spring.application.name=eventhub-api

# Configurações do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/eventhub_db
spring.datasource.username=eventhub_user
spring.datasource.password=eventhub_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate (JPA)
# O ddl-auto=update fará com que o Hibernate crie as tabelas automaticamente
# com base nas nossas classes Java (Entidades) que vamos criar logo mais.
# (Em um ambiente de produção real, usaríamos Flyway/Liquibase)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações do JWT
api.security.token.secret=MinhaChaveSecretaSuperLongaParaJWTQuePrecisaTerPeloMenos256BitsParaSerSegura!
